name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:

env:
  PYTHON_VERSION: 3.11

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install poetry
        run: pip install poetry

      - name: Determine dependencies
        run: poetry lock

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry

      - name: Install Dependencies using Poetry
        run: poetry install

      - name: Check formatting
        run: poetry run ruff format --check .
      
      - name: Lint
        run: poetry run ruff check .

  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install environment-modules (not lmod)
        run: |
          sudo apt-get update
          sudo apt-get install -y environment-modules

      - name: Test environment-modules
        run: |
          source /etc/profile.d/modules.sh
          type module
          module --help
        
      - uses: cvmfs-contrib/github-action-cvmfs@v4
      - name: Test CernVM-FS
        run: ls /cvmfs/sft.cern.ch/
      
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install poetry
        run: pip install poetry

      - name: Determine dependencies
        run: poetry lock

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Check cvmfs 
        run: |
          source /etc/profile.d/modules.sh
          sudo cvmfs_config setup
          export CVMFS_HTTP_PROXY=direct
          export CVMFS_CLIENT_PROFILE=single
          export CVMFS_REPOSITORIES='alice-ocdb.cern.ch,alice.cern.ch'
          cvmfs_config probe
          # cvmfs_config chksetup
          df -Th

      - name: Run pytest - with test_plugin.py different cernvmfs 
        run: |
          source /etc/profile.d/modules.sh
          poetry run coverage run -m pytest
          df -Th

      - name: Run Coverage
        run: poetry run coverage report -m
